version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: aitrainer
      POSTGRES_USER: trainer
      POSTGRES_PASSWORD: trainer
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - spring-postgres

volumes:
  postgres_data:

networks:
  spring-postgres:
    driver: bridge